apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-wrwo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-wrwo
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-wrwo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-wrwo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-wrwo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xtrn-tenant/rhtap-demo-app/hacbs-test-project-wrwo@sha256:fd6975e89a2e0d1cd35149085825bfb813268560f509fcaf40d7c9525bf9396c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
