apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-wrwo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xtrn-tenant/rhtap-demo-app/hacbs-test-project-wrwo@sha256:2ca951b017049bbfa916bef723e74be36f8834b96bcba7bb86a9ae2b5133120f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
